Adding temp directory for the cloned repository

diff --git a/run b/run
--- a/run
+++ b/run
@@ -9,6 +9,7 @@ if [ "$1" == "install" ]; then
     npm install typescript || echo "Error: typescript not installed correctly"
     npm install @types/node || echo "Error: @types/node not installed correctly"
     npm install axios || echo "Error: axios not installed correctly"
+    npm install tmp || echo "Error: tmp not installed correctly"
     echo "Modules installed successfully."
 else 
     tsc src/run.ts
