logging and PR + collaborator info graphql call

diff --git a/run b/run
--- a/run
+++ b/run
@@ -16,6 +16,7 @@ if [ "$1" == "install" ]; then
     npm install node-fetch@2 || echo "Error: node-fetch@2 not installed correctly"
     npm install @octokit/graphql || echo "Error: @octokit/graphql not installed correctly"
     npm install dotenv || echo "Error: dotenv not installed correctly"
+    npm install winston || echo "Error: winston not installed correctly"
     npm install @types/jest ts-jest 
     npm install istanbul-lib-coverage istanbul-reports nyc
     echo "Modules installed successfully."
